name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build -r

    - name: make artifact folder
      run: mkdir church-date-updater-linux; cp target/release/church-date-updater church-date-updater-linux/; cp church_date.html church-date-updater-linux/; cp -r pics/ church-date-updater-linux/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: church-date-updater-linux
        path: church-date-updater-linux/

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build -r

    - name: make artifact folder
      run: mkdir church-date-updater-windows; cp target/release/church-date-updater.exe church-date-updater-windows/; cp church_date.html church-date-updater-windows/; cp pics/ church-date-updater-windows/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: church-date-updater-windows
        path: church-date-updater-windows/
